packages:
  - "packages/*"
  - "examples/*"

engineStrict: true
strictPeerDependencies: false
autoInstallPeers: false
confirmModulesPurge: false

allowBuilds:
  esbuild: true

overrides:
  esbuild: ">=0.28.1 <0.29.0"
